# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Hemanth Sundaresan/Desktop/3050/SIMD Long Division/MAIN PROJECT.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Hemanth Sundaresan/Desktop/3050/SIMD Long Division/MAIN PROJECT.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  {c:/Users/Hemanth Sundaresan/Desktop/3050/ip_repo/AXI_LongDivision_1.0}
  {c:/Users/Hemanth Sundaresan/Desktop/3050/ip_repo}
} [current_project]
set_property ip_output_repo {c:/Users/Hemanth Sundaresan/Desktop/3050/SIMD Long Division/MAIN PROJECT.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Hemanth Sundaresan/Desktop/3050/SIMD Long Division/MAIN PROJECT.srcs/sources_1/new/DisplayDecoder.vhd}
  {C:/Users/Hemanth Sundaresan/Desktop/3050/SIMD Long Division/MAIN PROJECT.srcs/sources_1/new/REGOUT.vhd}
  {C:/Users/Hemanth Sundaresan/Desktop/3050/SIMD Long Division/MAIN PROJECT.srcs/sources_1/new/NBitLongDivision.vhd}
  {C:/Users/Hemanth Sundaresan/Desktop/3050/SIMD Long Division/MAIN PROJECT.srcs/sources_1/new/InputPairsROM.vhd}
  {C:/Users/Hemanth Sundaresan/Desktop/3050/SIMD Long Division/MAIN PROJECT.srcs/sources_1/new/DivisionToDisplayInterface.vhd}
  {C:/Users/Hemanth Sundaresan/Desktop/3050/SIMD Long Division/MAIN PROJECT.srcs/sources_1/new/DisplayController.vhd}
  {C:/Users/Hemanth Sundaresan/Desktop/3050/SIMD Long Division/MAIN PROJECT.srcs/sources_1/new/TopLevel_LongDivision.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Hemanth Sundaresan/Desktop/3050/SIMD Long Division/MAIN PROJECT.srcs/constrs_1/new/SIMDiv.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Hemanth Sundaresan/Desktop/3050/SIMD Long Division/MAIN PROJECT.srcs/constrs_1/new/SIMDiv.xdc}}]


synth_design -top TopLevel_LongDivision -part xc7a100tcsg324-1


write_checkpoint -force -noxdef TopLevel_LongDivision.dcp

catch { report_utilization -file TopLevel_LongDivision_utilization_synth.rpt -pb TopLevel_LongDivision_utilization_synth.pb }
