# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/simd_division/simd_division.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simd_division || ORIG_REF_NAME==simd_division}]

# IP: bd/simd_division/ip/simd_division_processing_system7_0_0/simd_division_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simd_division_processing_system7_0_0 || ORIG_REF_NAME==simd_division_processing_system7_0_0}]

# IP: bd/simd_division/ip/simd_division_my_simd_divider_0_0/simd_division_my_simd_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simd_division_my_simd_divider_0_0 || ORIG_REF_NAME==simd_division_my_simd_divider_0_0}]

# IP: bd/simd_division/ip/simd_division_ps7_0_axi_periph_0/simd_division_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simd_division_ps7_0_axi_periph_0 || ORIG_REF_NAME==simd_division_ps7_0_axi_periph_0}]

# IP: bd/simd_division/ip/simd_division_rst_ps7_0_50M_0/simd_division_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simd_division_rst_ps7_0_50M_0 || ORIG_REF_NAME==simd_division_rst_ps7_0_50M_0}]

# IP: bd/simd_division/ip/simd_division_auto_pc_0/simd_division_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simd_division_auto_pc_0 || ORIG_REF_NAME==simd_division_auto_pc_0}]

# XDC: bd/simd_division/simd_division_ooc.xdc
